package easy;

/*
    Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Find the letter that was added in t.
 */
public class FindTheDifference {

    public static void main(String... args) {

        FindTheDifference findTheDifference = new FindTheDifference();
        System.out.println(findTheDifference.findTheDifference("abcd", "abcde"));
    }

    public char findTheDifference(String s, String t) {

        long result = 0;
        char[] ch = t.toCharArray();
        for (char c : ch) result += c;
        ch = s.toCharArray();
        for (char c : ch) result -= c;
        return (char) result;
    }

}
